absolute-value:
  main: absolute-value.asm

binary-test:
  main: binary-test.asm

compare-test:
  main: compare-test.asm

console-test:
  main: console-test.asm

example:
  main: example.asm

first-function:
  main: first-function.asm

jump-not-equal-test:
  main: jump-not-equal-test.asm

store-test:
  main: store-test.asm
