absolute-value:
	- absolute-value.asm

binary-test:
	- binary-test.asm

compare-test:
	- compare-test.asm

console-test:
	- console-test.asm

example:
	- example.asm

first-function:
	- first-function.asm

jump-not-equal-test:
	- jump-not-equal-test.asm

store-test:
	- store-test.asm